--[[
    server/docs-generator.lua
    Regenerates docs/API_REGISTRY.md and docs/gamemodes/<id>.md whenever a
    GameMode registers, updates, or changes status. Writes via
    SaveResourceFile so the files land inside the resource's own folder.
]]

DocsGenerator = {}

local resourceName = GetCurrentResourceName()

local function writeDoc(relativePath, content)
    SaveResourceFile(resourceName, relativePath, content, -1)
end

local function joinList(list, prefix)
    prefix = prefix or '- '
    if not list or #list == 0 then
        return '_(none)_'
    end
    local lines = {}
    for _, v in ipairs(list) do
        lines[#lines + 1] = prefix .. tostring(v)
    end
    return table.concat(lines, '\n')
end

function DocsGenerator.GenerateForGameMode(record)
    local schema = GameModeSchema.Get(record.id)
    local schemaLines = {}
    if schema then
        for field, def in pairs(schema.fields) do
            local t = type(def) == 'table' and def.type or def
            schemaLines[#schemaLines + 1] = ('- `%s`: %s'):format(field, t)
        end
    end

    local content = ([[
# %s API

GameMode ID: `%s`
Version: %s
Schema Version: %s
Status: **%s**
Registered: %s
Last Updated: %s

## Capabilities
%s

## Statistics
%s

## Events
%s

## History Schema
%s

## Endpoints
- `GET /api/v1/me/gamemodes/%s`
- `GET /api/v1/me/gamemodes/%s/statistics`
- `GET /api/v1/me/gamemodes/%s/history`
- `GET /api/v1/me/gamemodes/%s/activity`

_This file is auto-generated by server-api. Do not edit by hand._
]]):format(
        record.displayName, record.id, record.version, record.schemaVersion,
        record.status, os.date('%Y-%m-%d', record.registeredAt), os.date('%Y-%m-%d', record.lastUpdatedAt),
        joinList(record.capabilities), joinList(record.statisticNames), joinList(record.events),
        (#schemaLines > 0 and table.concat(schemaLines, '\n') or '_(no schema registered)_'),
        record.id, record.id, record.id, record.id
    )

    writeDoc(('docs/gamemodes/%s.md'):format(record.id), content)
end

function DocsGenerator.GenerateRegistryIndex()
    local records = GameModeRegistry.GetAll()
    table.sort(records, function(a, b) return a.id < b.id end)

    local rows = {}
    for _, r in ipairs(records) do
        rows[#rows + 1] = ('| %s | %s | %s | %s |'):format(r.id, r.displayName, r.version, r.status)
    end

    local content = ([[
# API Registry

Auto-generated index of every GameMode registered with server-api.

| ID | Name | Version | Status |
|----|------|---------|--------|
%s

See `docs/gamemodes/<id>.md` for each GameMode's full contract.

_This file is auto-generated by server-api. Do not edit by hand._
]]):format(table.concat(rows, '\n'))

    writeDoc('docs/API_REGISTRY.md', content)
end
